/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resms.MyApp;

import resms.MyLib.InquiryForm;
import java.util.ArrayList;
import resms.Factory.PaymentForm;
import resms.MyLib.Lot;
import resms.MyLib.Lot_List;
import resms.MyLib.ReservationForm;

/**
 *
 * @author Buena, Lucas, Lumba, Magana, Paita, Tambagan
 */
public class MainForm1 extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Lot_List LotList;
    
    public MainForm1(Lot_List LotList) {
        initComponents();
        this.LotList = LotList;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filteredButton = new javax.swing.JButton();
        unfilteredButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reserveButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Real Estate Management System");

        filteredButton.setBackground(new java.awt.Color(255, 255, 204));
        filteredButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        filteredButton.setText("View Available Lots");
        filteredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filteredButtonActionPerformed(evt);
            }
        });

        unfilteredButton.setBackground(new java.awt.Color(255, 255, 204));
        unfilteredButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        unfilteredButton.setText("View All Lots");
        unfilteredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfilteredButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 255, 204));
        searchButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        reserveButton.setBackground(new java.awt.Color(255, 255, 204));
        reserveButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        reserveButton.setText("Reserve A Lot");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        paymentButton.setBackground(new java.awt.Color(255, 255, 204));
        paymentButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentButton.setText("Buy A Lot");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filteredButton)
                            .addComponent(unfilteredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(filteredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unfilteredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(reserveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentButton)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        InquiryForm newSearch = new InquiryForm(LotList);
        newSearch.setVisible(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        ReservationForm reservation = new ReservationForm(LotList);
        reservation.setVisible(true);
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        PaymentForm payment = new PaymentForm(LotList);
        payment.setVisible(true);
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void unfilteredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfilteredButtonActionPerformed
        jTextArea1.setText("");
        getLots();
    }//GEN-LAST:event_unfilteredButtonActionPerformed

    private void filteredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filteredButtonActionPerformed
        jTextArea1.setText("");
        getAvailableLots();
    }//GEN-LAST:event_filteredButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void getAvailableLots() {
        int i;
        int count = 0;// number of available lots

        for (i = 0; i < LotList.getListSize(); i++) {
            if ("For Sale".equals(LotList.getStatus(i))) {
                jTextArea1.append(
                        "Lot Num: " + LotList.getLotNum(i) + "\n"
                        + "Size: " + LotList.getLotSize(i) + " sqm" + "\n"
                        + "Location: Block " + LotList.getBlock(i) + " Lot " + LotList.getLot(i) + "\n"
                        + "Price: Php " + LotList.getPrice(i) + "\n"
                        + "\n"
                );
                count++;
            }//ends if statement
        }//ends for loop
    }//ends getAvailableLots() method
    
    public void getLots() {
        int i;
        int count = 0;// number of available lots

        for (i = 0; i < LotList.getListSize(); i++) {
                jTextArea1.append(
                        "Lot Num: " + LotList.getLotNum(i) + "\n"
                        + "Status: " + LotList.getStatus(i) + "\n"
                        + "Size: " + LotList.getLotSize(i) + " sqm" + "\n"
                        + "Location: Block " + LotList.getBlock(i) + " Lot " + LotList.getLot(i) + "\n"
                        + "Price: Php " + LotList.getPrice(i) + "\n"
                        + "\n"
                );
        }//ends for loop
    }//ends getAvailableLots() method
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filteredButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton reserveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton unfilteredButton;
    // End of variables declaration//GEN-END:variables
}



//  Buena, Lucas, Lumba, Magana, Paita, Tambagan
//  CSS123L - BM3 - FINAL PROJECT
//  08/07/2023
